export const letterAnimation = {
    v: "5.5.7",
    meta: {
      g: "LottieFiles AE 0.1.21",
      a: "Keikhosrow",
      k: "Message, letter",
      d: "Notification read",
      tc: "",
    },
    fr: 60,
    ip: 0,
    op: 65,
    w: 128,
    h: 128,
    nm: "notifications",
    ddd: 0,
    assets: [],
    layers: [
      {
        ddd: 0,
        ind: 1,
        ty: 4,
        nm: "Layer 1/no notif Outlines",
        sr: 1,
        ks: {
          o: { a: 0, k: 100, ix: 11 },
          r: { a: 0, k: 0, ix: 10 },
          p: { a: 0, k: [64, 64, 0], ix: 2 },
          a: { a: 0, k: [58, 52, 0], ix: 1 },
          s: { a: 0, k: [100, 100, 100], ix: 6 },
        },
        ao: 0,
        shapes: [
          {
            ty: "gr",
            it: [
              {
                ind: 0,
                ty: "sh",
                ix: 1,
                ks: {
                  a: 0,
                  k: {
                    i: [
                      [0, 0],
                      [0.194, -0.266],
                      [0.678, 0.001],
                      [0, 0],
                      [0.544, 0.35],
                      [0.181, 0.238],
                      [0, 0],
                      [0, 0],
                      [-0.955, -0.524],
                      [0, 0],
                    ],
                    o: [
                      [-0.198, 0.271],
                      [-0.56, 0.382],
                      [0, 0],
                      [-0.648, 0],
                      [-0.181, -0.237],
                      [0, 0],
                      [0, 0],
                      [0.955, -0.524],
                      [0, 0],
                      [0, 0],
                    ],
                    v: [
                      [54.702, 14.126],
                      [54.117, 14.932],
                      [52.215, 15.518],
                      [-52.335, 15.518],
                      [-54.161, 14.98],
                      [-54.702, 14.266],
                      [-54.521, 14.167],
                      [-1.592, -14.995],
                      [1.477, -14.995],
                      [54.523, 14.027],
                    ],
                    c: true,
                  },
                  ix: 2,
                },
                nm: "Path 1",
                mn: "ADBE Vector Shape - Group",
                hd: false,
              },
              {
                ty: "fl",
                c: {
                  a: 0,
                  k: [0.152999997606, 0.681999954523, 0.375999989229, 1],
                  ix: 4,
                },
                o: { a: 0, k: 100, ix: 5 },
                r: 1,
                bm: 0,
                nm: "Fill 1",
                mn: "ADBE Vector Graphic - Fill",
                hd: false,
              },
              {
                ty: "tr",
                p: { a: 0, k: [57.981, 85.933], ix: 2 },
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                r: { a: 0, k: 0, ix: 6 },
                o: { a: 0, k: 100, ix: 7 },
                sk: { a: 0, k: 0, ix: 4 },
                sa: { a: 0, k: 0, ix: 5 },
                nm: "Transform",
              },
            ],
            nm: "bottomgreen",
            np: 2,
            cix: 2,
            bm: 0,
            ix: 1,
            mn: "ADBE Vector Group",
            hd: false,
          },
          {
            ty: "gr",
            it: [
              {
                ind: 0,
                ty: "sh",
                ix: 1,
                ks: {
                  a: 0,
                  k: {
                    i: [
                      [18.459, -10.368],
                      [18.632, 10.449],
                      [0, 0],
                      [-1.859, -0.004],
                      [0, 0],
                      [-0.006, 1.958],
                      [0, 0],
                    ],
                    o: [
                      [-18.631, -10.448],
                      [0, 0],
                      [0.006, 1.958],
                      [0, 0],
                      [1.858, -0.004],
                      [0, 0],
                      [-18.458, 10.368],
                    ],
                    v: [
                      [0.26, -0.052],
                      [-55.635, -31.398],
                      [-55.635, 27.851],
                      [-52.263, 31.398],
                      [52.264, 31.398],
                      [55.635, 27.851],
                      [55.635, -31.155],
                    ],
                    c: true,
                  },
                  ix: 2,
                },
                nm: "Path 1",
                mn: "ADBE Vector Shape - Group",
                hd: false,
              },
              {
                ty: "st",
                c: {
                  a: 0,
                  k: [0.078000005086, 0.078000005086, 0.219999994016, 1],
                  ix: 3,
                },
                o: { a: 0, k: 100, ix: 4 },
                w: { a: 0, k: 0.75, ix: 5 },
                lc: 1,
                lj: 1,
                ml: 10,
                bm: 0,
                nm: "Stroke 1",
                mn: "ADBE Vector Graphic - Stroke",
                hd: false,
              },
              {
                ty: "fl",
                c: { a: 0, k: [1, 1, 1, 1], ix: 4 },
                o: { a: 0, k: 100, ix: 5 },
                r: 1,
                bm: 0,
                nm: "Fill 1",
                mn: "ADBE Vector Graphic - Fill",
                hd: false,
              },
              {
                ty: "tr",
                p: { a: 0, k: [57.88, 70.598], ix: 2 },
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                r: { a: 0, k: 0, ix: 6 },
                o: { a: 0, k: 100, ix: 7 },
                sk: { a: 0, k: 0, ix: 4 },
                sa: { a: 0, k: 0, ix: 5 },
                nm: "Transform",
              },
            ],
            nm: "letterbody",
            np: 3,
            cix: 2,
            bm: 0,
            ix: 2,
            mn: "ADBE Vector Group",
            hd: false,
          },
          {
            ty: "gr",
            it: [
              {
                ty: "gr",
                it: [
                  {
                    ind: 0,
                    ty: "sh",
                    ix: 1,
                    ks: {
                      a: 0,
                      k: {
                        i: [
                          [0, 0],
                          [0, 0],
                          [0, 0],
                        ],
                        o: [
                          [0, 0],
                          [0, 0],
                          [0, 0],
                        ],
                        v: [
                          [12.809, -9.639],
                          [-4.803, 9.639],
                          [-12.809, 0.877],
                        ],
                        c: false,
                      },
                      ix: 2,
                    },
                    nm: "Path 1",
                    mn: "ADBE Vector Shape - Group",
                    hd: false,
                  },
                  {
                    ty: "tm",
                    s: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.833], y: [0.833] },
                          o: { x: [0.167], y: [0.167] },
                          t: 48,
                          s: [100],
                        },
                        { t: 62, s: [0] },
                      ],
                      ix: 1,
                      x: "var $bm_rt;\n$bm_rt = content('letter').content('Checkmark').content('Trim Paths 1').start;",
                    },
                    e: { a: 0, k: 100, ix: 2 },
                    o: { a: 0, k: 0, ix: 3 },
                    m: 2,
                    ix: 2,
                    nm: "Trim Paths 1",
                    mn: "ADBE Vector Filter - Trim",
                    hd: false,
                  },
                  {
                    ty: "st",
                    c: {
                      a: 0,
                      k: [0.152999997606, 0.681999954523, 0.375999989229, 1],
                      ix: 3,
                    },
                    o: { a: 0, k: 100, ix: 4 },
                    w: { a: 0, k: 3, ix: 5 },
                    lc: 2,
                    lj: 2,
                    bm: 0,
                    nm: "Stroke 1",
                    mn: "ADBE Vector Graphic - Stroke",
                    hd: false,
                  },
                  {
                    ty: "tr",
                    p: { a: 0, k: [87.941, 9.639], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: "Transform",
                  },
                ],
                nm: "Checkmark",
                np: 3,
                cix: 2,
                bm: 0,
                ix: 1,
                mn: "ADBE Vector Group",
                hd: false,
              },
              {
                ty: "gr",
                it: [
                  {
                    ind: 0,
                    ty: "sh",
                    ix: 1,
                    ks: {
                      a: 0,
                      k: {
                        i: [
                          [0, 0],
                          [0, 0],
                          [0.066, 0.882],
                          [-0.878, 0.066],
                          [-0.079, -0.006],
                          [0, 0],
                          [0.066, -0.881],
                          [0.787, -0.059],
                        ],
                        o: [
                          [0, 0],
                          [-0.878, 0.066],
                          [-0.065, -0.881],
                          [0.08, -0.006],
                          [0, 0],
                          [0.879, 0.066],
                          [-0.059, 0.789],
                          [0, 0],
                        ],
                        v: [
                          [20.594, 1.566],
                          [-20.36, 1.566],
                          [-22.07, 0.09],
                          [-20.599, -1.626],
                          [-20.36, -1.626],
                          [20.598, -1.626],
                          [22.069, 0.09],
                          [20.598, 1.566],
                        ],
                        c: true,
                      },
                      ix: 2,
                    },
                    nm: "Path 1",
                    mn: "ADBE Vector Shape - Group",
                    hd: false,
                  },
                  {
                    ty: "fl",
                    c: {
                      a: 0,
                      k: [0.902000038297, 0.902000038297, 0.902000038297, 1],
                      ix: 4,
                    },
                    o: { a: 0, k: 100, ix: 5 },
                    r: 1,
                    bm: 0,
                    nm: "Fill 1",
                    mn: "ADBE Vector Graphic - Fill",
                    hd: false,
                  },
                  {
                    ty: "tr",
                    p: { a: 0, k: [56.08, 44.211], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                          o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                          t: 40,
                          s: [0, 100],
                        },
                        { t: 51, s: [100, 100] },
                      ],
                      ix: 3,
                      x: "var $bm_rt;\n$bm_rt = content('letter').content('3rdline').transform.scale;",
                    },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: "Transform",
                  },
                ],
                nm: "3rdline",
                np: 2,
                cix: 2,
                bm: 0,
                ix: 2,
                mn: "ADBE Vector Group",
                hd: false,
              },
              {
                ty: "gr",
                it: [
                  {
                    ind: 0,
                    ty: "sh",
                    ix: 1,
                    ks: {
                      a: 0,
                      k: {
                        i: [
                          [0.786, -0.059],
                          [0, 0],
                          [-0.066, 0.881],
                          [-0.787, 0.06],
                          [0, 0],
                          [0.066, -0.88],
                        ],
                        o: [
                          [0, 0],
                          [-0.879, -0.066],
                          [0.059, -0.789],
                          [0, 0],
                          [0.878, 0.066],
                          [-0.059, 0.789],
                        ],
                        v: [
                          [17.195, 1.596],
                          [-17.195, 1.596],
                          [-18.665, -0.12],
                          [-17.195, -1.596],
                          [17.195, -1.596],
                          [18.665, 0.12],
                        ],
                        c: true,
                      },
                      ix: 2,
                    },
                    nm: "Path 1",
                    mn: "ADBE Vector Shape - Group",
                    hd: false,
                  },
                  {
                    ty: "fl",
                    c: {
                      a: 0,
                      k: [0.152999997606, 0.681999954523, 0.375999989229, 1],
                      ix: 4,
                    },
                    o: { a: 0, k: 100, ix: 5 },
                    r: 1,
                    bm: 0,
                    nm: "Fill 1",
                    mn: "ADBE Vector Graphic - Fill",
                    hd: false,
                  },
                  {
                    ty: "tr",
                    p: { a: 0, k: [56.295, 32.021], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                          o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                          t: 34,
                          s: [0, 100],
                        },
                        { t: 47, s: [100, 100] },
                      ],
                      ix: 3,
                      x: "var $bm_rt;\n$bm_rt = content('letter').content('1stline').transform.scale;",
                    },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: "Transform",
                  },
                ],
                nm: "1stline",
                np: 2,
                cix: 2,
                bm: 0,
                ix: 3,
                mn: "ADBE Vector Group",
                hd: false,
              },
              {
                ty: "gr",
                it: [
                  {
                    ind: 0,
                    ty: "sh",
                    ix: 1,
                    ks: {
                      a: 0,
                      k: {
                        i: [
                          [0, 0],
                          [0, 0],
                          [0.066, 0.882],
                          [-0.878, 0.066],
                          [-0.079, -0.006],
                          [0, 0],
                          [0.066, -0.881],
                          [0.787, -0.059],
                        ],
                        o: [
                          [0, 0],
                          [-0.878, 0.066],
                          [-0.065, -0.881],
                          [0.08, -0.006],
                          [0, 0],
                          [0.879, 0.066],
                          [-0.059, 0.789],
                          [0, 0],
                        ],
                        v: [
                          [20.594, 1.566],
                          [-20.36, 1.566],
                          [-22.07, 0.09],
                          [-20.599, -1.626],
                          [-20.36, -1.626],
                          [20.598, -1.626],
                          [22.069, 0.09],
                          [20.598, 1.566],
                        ],
                        c: true,
                      },
                      ix: 2,
                    },
                    nm: "Path 1",
                    mn: "ADBE Vector Shape - Group",
                    hd: false,
                  },
                  {
                    ty: "fl",
                    c: {
                      a: 0,
                      k: [0.902000038297, 0.902000038297, 0.902000038297, 1],
                      ix: 4,
                    },
                    o: { a: 0, k: 100, ix: 5 },
                    r: 1,
                    bm: 0,
                    nm: "Fill 1",
                    mn: "ADBE Vector Graphic - Fill",
                    hd: false,
                  },
                  {
                    ty: "tr",
                    p: { a: 0, k: [56.08, 38.231], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                          o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                          t: 41,
                          s: [0, 100],
                        },
                        { t: 50, s: [100, 100] },
                      ],
                      ix: 3,
                      x: "var $bm_rt;\n$bm_rt = content('letter').content('2ndline').transform.scale;",
                    },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: "Transform",
                  },
                ],
                nm: "2ndline",
                np: 2,
                cix: 2,
                bm: 0,
                ix: 4,
                mn: "ADBE Vector Group",
                hd: false,
              },
              {
                ty: "gr",
                it: [
                  {
                    ind: 0,
                    ty: "sh",
                    ix: 1,
                    ks: {
                      a: 0,
                      k: {
                        i: [
                          [0.786, -0.06],
                          [0, 0],
                          [0.066, 0.881],
                          [-0.878, 0.066],
                          [-0.08, -0.006],
                          [0, 0],
                          [0.066, -0.881],
                        ],
                        o: [
                          [0, 0],
                          [-0.879, 0.066],
                          [-0.066, -0.881],
                          [0.08, -0.006],
                          [0, 0],
                          [0.878, 0.066],
                          [-0.059, 0.789],
                        ],
                        v: [
                          [2.903, 1.566],
                          [-2.664, 1.566],
                          [-4.374, 0.09],
                          [-2.904, -1.626],
                          [-2.664, -1.626],
                          [2.903, -1.626],
                          [4.374, 0.09],
                        ],
                        c: true,
                      },
                      ix: 2,
                    },
                    nm: "Path 1",
                    mn: "ADBE Vector Shape - Group",
                    hd: false,
                  },
                  {
                    ty: "fl",
                    c: {
                      a: 0,
                      k: [0.152999997606, 0.681999954523, 0.375999989229, 1],
                      ix: 4,
                    },
                    o: { a: 0, k: 100, ix: 5 },
                    r: 1,
                    bm: 0,
                    nm: "Fill 1",
                    mn: "ADBE Vector Graphic - Fill",
                    hd: false,
                  },
                  {
                    ty: "tr",
                    p: { a: 0, k: [30.119, 12.325], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                          o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                          t: 28,
                          s: [0, 100],
                        },
                        { t: 38, s: [100, 100] },
                      ],
                      ix: 3,
                      x: "var $bm_rt;\n$bm_rt = content('letter').content('topleft1st').transform.scale;",
                    },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: "Transform",
                  },
                ],
                nm: "topleft1st",
                np: 2,
                cix: 2,
                bm: 0,
                ix: 5,
                mn: "ADBE Vector Group",
                hd: false,
              },
              {
                ty: "gr",
                it: [
                  {
                    ind: 0,
                    ty: "sh",
                    ix: 1,
                    ks: {
                      a: 0,
                      k: {
                        i: [
                          [0.787, -0.059],
                          [0, 0],
                          [-0.066, 0.881],
                          [-0.787, 0.059],
                          [0, 0],
                          [0.066, -0.881],
                        ],
                        o: [
                          [0, 0],
                          [-0.878, -0.066],
                          [0.059, -0.789],
                          [0, 0],
                          [0.878, 0.066],
                          [-0.059, 0.789],
                        ],
                        v: [
                          [6.064, 1.596],
                          [-6.064, 1.596],
                          [-7.535, -0.12],
                          [-6.064, -1.596],
                          [6.064, -1.596],
                          [7.535, 0.12],
                        ],
                        c: true,
                      },
                      ix: 2,
                    },
                    nm: "Path 1",
                    mn: "ADBE Vector Shape - Group",
                    hd: false,
                  },
                  {
                    ty: "fl",
                    c: {
                      a: 0,
                      k: [0.902000038297, 0.902000038297, 0.902000038297, 1],
                      ix: 4,
                    },
                    o: { a: 0, k: 100, ix: 5 },
                    r: 1,
                    bm: 0,
                    nm: "Fill 1",
                    mn: "ADBE Vector Graphic - Fill",
                    hd: false,
                  },
                  {
                    ty: "tr",
                    p: { a: 0, k: [33.521, 17.68], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: {
                      a: 1,
                      k: [
                        {
                          i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                          o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                          t: 32,
                          s: [0, 100],
                        },
                        { t: 41, s: [100, 100] },
                      ],
                      ix: 3,
                      x: "var $bm_rt;\n$bm_rt = content('letter').content('topleft2nd').transform.scale;",
                    },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: "Transform",
                  },
                ],
                nm: "topleft2nd",
                np: 2,
                cix: 2,
                bm: 0,
                ix: 6,
                mn: "ADBE Vector Group",
                hd: false,
              },
              {
                ty: "gr",
                it: [
                  {
                    ind: 0,
                    ty: "sh",
                    ix: 1,
                    ks: {
                      a: 0,
                      k: {
                        i: [
                          [0, 0],
                          [0, 29.889],
                          [-2.086, 0.006],
                          [0, 0],
                          [-0.006, -4.447],
                          [0, -29.927],
                        ],
                        o: [
                          [0, 0],
                          [0.005, -4.447],
                          [0, 0],
                          [2.086, 0.006],
                          [0, 29.928],
                          [0, 0],
                        ],
                        v: [
                          [-38.316, 33.773],
                          [-38.128, -25.719],
                          [-34.344, -33.773],
                          [34.533, -33.773],
                          [38.316, -25.719],
                          [38.243, 33.177],
                        ],
                        c: false,
                      },
                      ix: 2,
                    },
                    nm: "Path 1",
                    mn: "ADBE Vector Shape - Group",
                    hd: false,
                  },
                  {
                    ty: "st",
                    c: {
                      a: 0,
                      k: [0.216000007181, 0.20800000359, 0.517999985639, 1],
                      ix: 3,
                    },
                    o: { a: 0, k: 100, ix: 4 },
                    w: { a: 0, k: 0.25, ix: 5 },
                    lc: 1,
                    lj: 1,
                    ml: 10,
                    bm: 0,
                    nm: "Stroke 1",
                    mn: "ADBE Vector Graphic - Stroke",
                    hd: false,
                  },
                  {
                    ty: "fl",
                    c: {
                      a: 0,
                      k: [0.969000004787, 0.969000004787, 0.969000004787, 1],
                      ix: 4,
                    },
                    o: { a: 0, k: 100, ix: 5 },
                    r: 1,
                    bm: 0,
                    nm: "Fill 1",
                    mn: "ADBE Vector Graphic - Fill",
                    hd: false,
                  },
                  {
                    ty: "tr",
                    p: { a: 0, k: [58.113, 36.773], ix: 2 },
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    r: { a: 0, k: 0, ix: 6 },
                    o: { a: 0, k: 100, ix: 7 },
                    sk: { a: 0, k: 0, ix: 4 },
                    sa: { a: 0, k: 0, ix: 5 },
                    nm: "Transform",
                  },
                ],
                nm: "fillup",
                np: 3,
                cix: 2,
                bm: 0,
                ix: 7,
                mn: "ADBE Vector Group",
                hd: false,
              },
              {
                ty: "tr",
                p: {
                  a: 1,
                  k: [
                    {
                      i: { x: 0.833, y: 0.833 },
                      o: { x: 0.167, y: 0.167 },
                      t: 0,
                      s: [0, 51],
                      to: [0, -9],
                      ti: [0, 8.5],
                    },
                    {
                      i: { x: 0.833, y: 0.833 },
                      o: { x: 0.167, y: 0.167 },
                      t: 23,
                      s: [0, -3],
                      to: [0, -8.5],
                      ti: [0, -0.5],
                    },
                    { t: 29, s: [0, 0] },
                  ],
                  ix: 2,
                  x: "var $bm_rt;\n$bm_rt = content('letter').transform.position;",
                },
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                r: { a: 0, k: 0, ix: 6 },
                o: {
                  a: 1,
                  k: [
                    {
                      i: { x: [0.833], y: [0.833] },
                      o: { x: [0.167], y: [0.167] },
                      t: 0,
                      s: [0],
                    },
                    { t: 11, s: [100] },
                  ],
                  ix: 7,
                  x: "var $bm_rt;\n$bm_rt = content('letter').transform.opacity;",
                },
                sk: { a: 0, k: 0, ix: 4 },
                sa: { a: 0, k: 0, ix: 5 },
                nm: "Transform",
              },
            ],
            nm: "letter",
            np: 7,
            cix: 2,
            bm: 0,
            ix: 3,
            mn: "ADBE Vector Group",
            hd: false,
          },
          {
            ty: "gr",
            it: [
              {
                ind: 0,
                ty: "sh",
                ix: 1,
                ks: {
                  a: 0,
                  k: {
                    i: [
                      [0, 0],
                      [0, 0],
                      [0, 0],
                      [4.005, -2.249],
                      [0, 0],
                      [0, 0],
                    ],
                    o: [
                      [0, 0],
                      [0, 0],
                      [-4.004, -2.253],
                      [0, 0],
                      [0, 0],
                      [0, 0],
                    ],
                    v: [
                      [55.751, 14.815],
                      [53.407, 13.719],
                      [6.654, -12.598],
                      [-6.283, -12.604],
                      [-53.154, 13.721],
                      [-55.751, 14.854],
                    ],
                    c: false,
                  },
                  ix: 2,
                },
                nm: "Path 1",
                mn: "ADBE Vector Shape - Group",
                hd: false,
              },
              {
                ty: "st",
                c: { a: 0, k: [0, 0, 0, 1], ix: 3 },
                o: { a: 0, k: 100, ix: 4 },
                w: { a: 0, k: 0.75, ix: 5 },
                lc: 1,
                lj: 1,
                ml: 10,
                bm: 0,
                nm: "Stroke 1",
                mn: "ADBE Vector Graphic - Stroke",
                hd: false,
              },
              {
                ty: "fl",
                c: { a: 0, k: [1, 1, 1, 1], ix: 4 },
                o: { a: 0, k: 100, ix: 5 },
                r: 1,
                bm: 0,
                nm: "Fill 1",
                mn: "ADBE Vector Graphic - Fill",
                hd: false,
              },
              {
                ty: "tr",
                p: { a: 0, k: [57.626, 24.408], ix: 2 },
                a: { a: 0, k: [0, 0], ix: 1 },
                s: { a: 0, k: [100, 100], ix: 3 },
                r: { a: 0, k: 0, ix: 6 },
                o: { a: 0, k: 100, ix: 7 },
                sk: { a: 0, k: 0, ix: 4 },
                sa: { a: 0, k: 0, ix: 5 },
                nm: "Transform",
              },
            ],
            nm: "lettertopon",
            np: 3,
            cix: 2,
            bm: 0,
            ix: 4,
            mn: "ADBE Vector Group",
            hd: false,
          },
        ],
        ip: 0,
        op: 180,
        st: 0,
        bm: 0,
      },
    ],
    markers: [],
  };