import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import Lottie from "react-lottie";

import Switch from "../components/Switch";
import CustomTooltip from "../components/CustomTooltip";
import ZoominCard from "../components/ZoominCard";
import { SocialIcon } from "react-social-icons";

import styles from "../styles/Home.module.css";
import { letterAnimation } from "../animation";

export interface FormState {
  name: string;
  email: string;
  message: string;
}

const Home: NextPage = () => {
  const [isLoading, setIsLoading] = useState<boolean>();
  const [showMenu, setShowMenu] = useState<boolean>(false);

  const [formState, setFormState] = useState<FormState>({
    name: "",
    email: "",
    message: "",
  });

  // default options for the lottie animation
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: letterAnimation,
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Gats Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={``}>
        <div className="flex dark:text-white absolute w-full top-0 z-10 justify-between p-4 md:px-16">
          <Link href="/">
            <a href="">
              <Image
                width="100px"
                height="30px"
                className="m-4 w-24 md:w-32 md:max-h-12"
                src="/assets/icons/branding/gats-dev.png"
                alt="Personal Branding logo"
              />
            </a>
          </Link>
          <div className="flex gap-6 items-center mie-4">
            <div className="dark:text-white relative">
              <div
                onClick={() => {
                  setShowMenu(!showMenu);
                }}
                className={`md:hidden cursor-pointer ${styles.arrow} ${
                  showMenu ? styles.dropArrow : ""
                }`}
              >
                Menu
              </div>
              {showMenu && (
                <div className="flex absolute top-10 flex-col gap-4">
                  <a
                    onClick={() => {
                      setShowMenu(false);
                    }}
                    href={"https://blogs.gats.dev/"}
                    target="_"
                    className={`${styles.borderBottomHover} cursor-pointer`}
                  >
                    Blogs
                  </a>
                  <a
                    href={`https://github.com/gat786`}
                    onClick={() => {
                      setShowMenu(false);
                    }}
                    target="_"
                    className={`${styles.borderBottomHover} cursor-pointer`}
                  >
                    Projects
                  </a>
                  <a
                    href="#social-section"
                    onClick={() => {
                      setShowMenu(false);
                    }}
                    className={`${styles.borderBottomHover} cursor-pointer`}
                  >
                    Connect
                  </a>
                </div>
              )}
            </div>

            <div className="hidden md:flex gap-6">
              <a
                href={"https://blogs.gats.dev/"}
                target="_"
                className={`${styles.borderBottomHover} cursor-pointer`}
              >
                Blogs
              </a>
              <a
                href={`https://github.com/gat786`}
                target="_"
                className={`${styles.borderBottomHover} cursor-pointer`}
              >
                Projects
              </a>
              <a
                href="#social-section"
                className={`${styles.borderBottomHover} cursor-pointer`}
              >
                Connect
              </a>
            </div>
            <Switch />
          </div>
        </div>
        <div
          className={`dark:bg-black bg-gray-200 dark:text-white ${styles.scrollSnaps}`}
        >
          <section
            id={`#top-section`}
            className={`flex flex-col h-screen md:px-4`}
          >
            <div className="flex flex-col justify-center gap-8 md:flex-row flex-grow">
              <div className="md:hidden flex items-center w-full justify-center">
                <Image
                  className="rounded-full w-1/2 border-8 border-gray-500"
                  src={"/assets/images/profile.webp"}
                  height={200}
                  width={200}
                  alt=""
                />
              </div>

              <div className="dark:text-white text-center md:text-start text-3xl lg:text-4xl md:w-2/4 md:mli-16 mli-8 flex flex-col gap-4 justify-center">
                Hi!
                <div className={`inline ${styles.lastTwoBold}`}>
                  I am Ganesh Tiwari
                </div>
                <div className="inline leading-relaxed">
                  I am a Software Engineer currently working as a UI Engineer
                </div>
              </div>

              <div className="md:flex hidden items-center w-1/4 justify-center">
                <Image
                  className="rounded-full border-8 max-h-96 border-gray-500"
                  height={300}
                  width={300}
                  src={"/assets/images/profile.webp"}
                  alt=""
                />
              </div>
            </div>
          </section>
          <section
            className={`flex md:flex-row flex-col justify-center gap-8 md:px-8 items-center h-screen`}
          >
            <div className="flex flex-col py-16 lg:h-screen lg:justify-center md:w-1/2 gap-8">
              <div className="text-4xl pis-8">
                I make Applications for every Platform
              </div>
              <div className="inline-flex flex-row flex-wrap text-2xl mis-8">
                <div className="tooltip relative">
                  Android, &nbsp;
                  <CustomTooltip
                    childIcon={"/assets/icons/logos/android-bot.svg"}
                  />
                </div>
                <div className="tooltip relative">
                  Windows, &nbsp;
                  <CustomTooltip
                    childIcon={"/assets/icons/logos/windows-logo.svg"}
                  />
                </div>
                <div className="tooltip relative">
                  Linux, &nbsp;
                  <CustomTooltip
                    childIcon={"/assets/icons/logos/linux-logo.svg"}
                  />
                </div>
                <div className="tooltip relative">
                  Web &nbsp;
                  <CustomTooltip
                    childIcon={"/assets/icons/logos/html-logo.svg"}
                  />
                </div>
                and &nbsp;
                <div className="tooltip relative">
                  Server. &nbsp;
                  <CustomTooltip
                    childIcon={"/assets/icons/logos/server-farm.svg"}
                  />
                </div>
              </div>
            </div>

            <div className={`relative w-2/3 lg:w-1/3 ${styles.aspectRatio}`}>
              <ZoominCard
                customBG={"bg-black"}
                customFill={"object-fit"}
                imageAddress={"/assets/icons/logos/dev-voice.svg"}
                currentPositionCss="top-0 left-0"
              />
              <ZoominCard
                imageAddress={"/assets/icons/logos/github-browser-logo.svg"}
                currentPositionCss="top-0 right-0"
              />
              <ZoominCard
                imageAddress={"/assets/icons/logos/styava-communities-logo.svg"}
                currentPositionCss="top-0 right-0 left-0 bottom-0 m-auto"
              />
              <ZoominCard
                imageAddress={"/assets/icons/logos/ric-bot.webp"}
                currentPositionCss="bottom-0 left-0"
              />
              <ZoominCard
                imageAddress={"/assets/icons/logos/openlocker-logo.png"}
                currentPositionCss="bottom-0 right-0"
              />
            </div>
          </section>
          <section
            id="social-section"
            className={`flex md:flex-row flex-col gap-8 md:px-8 items-center justify-center h-screen`}
          >
            <div className="text-3xl mli-8 flex flex-col h-full justify-center gap-8">
              <div>
                I create contents as Blogs, Videos and Different Technical
                Sessions.
              </div>
              <div className="text-2xl">
                You can find me on the following Social Networks
              </div>

              <div className="grid grid-flow-row-dense grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 items-center gap-6 ">
                <SocialIcon
                  network="twitter"
                  target="_blank"
                  url="https://twitter.com/igat786"
                />
                <SocialIcon
                  network="instagram"
                  target="_blank"
                  url="https://instagram.com/gats.dev"
                />
                <SocialIcon
                  network="facebook"
                  target="_blank"
                  url="https://fb.com/gat786"
                />
                <SocialIcon
                  network="youtube"
                  target="_blank"
                  url="https://www.youtube.com/channel/UCeP2cJ51JXyEQEVyi3prG8g"
                />
                <SocialIcon
                  network="medium"
                  target="_blank"
                  url="https://medium.com/@gat786"
                />
                <SocialIcon
                  network="linkedin"
                  target="_blank"
                  url="https://linkedin.com/in/gat786"
                />
                <SocialIcon
                  network="github"
                  target="_blank"
                  url="https://github.com/gat786"
                />

                <a href="https://dev.to/gat786" target="_">
                  <Image
                    src={"/assets/icons/logos/dev-to.svg"}
                    height={60}
                    width={60}
                    alt="Dev.To Logo"
                    className="w-12 h-12 p-1 border-white border"
                  />
                </a>
              </div>
            </div>
          </section>

          <section
            className={`flex md:flex-row flex-col gap-8 justify-center w-full p-8 md:items-center h-screen`}
          >
            <div className="flex flex-col h-full w-full justify-center md:flex-row md:px-8">
              <form
                name="contact-me"
                className=" flex flex-col justify-center w-full md:w-1/2 gap-4 p-4"
                method="POST"
                onSubmit={async (event) => {
                  event.preventDefault();
                  console.log(`submitting`);
                  setIsLoading(true);
                  // setTimeout(() => {
                  //   console.log(`done`);
                  // },4000)
                  // await dispatch(queryActions.sendEmail({ data: formState }));
                  setIsLoading(false);
                }}
                data-netlify="true"
              >
                <h1 className="text-2xl md:text-4xl font-semibold">
                  If you have any queries send em here
                </h1>
                <input type="hidden" name="form-name" value="contact-me" />
                <div className="flex flex-col gap-2">
                  <label
                    className="text-black dark:text-white"
                    htmlFor="name-input"
                  >
                    Your Name
                  </label>
                  <input
                    name="name-input"
                    id="name-input"
                    required
                    aria-required
                    value={formState.name}
                    onChange={(event) => {
                      setFormState({ ...formState, name: event.target.value });
                    }}
                    className="p-2 text-base text-black w-full"
                    placeholder="Your Name"
                    type="text"
                  />
                </div>
                <div className="flex flex-col gap-2">
                  <label className="" htmlFor="query-input">
                    Your Query
                  </label>
                  <textarea
                    name="query-input"
                    required
                    aria-required
                    id="query-input"
                    value={formState.message}
                    onChange={(event) => {
                      setFormState({
                        ...formState,
                        message: event.target.value,
                      });
                    }}
                    className="p-2 text-black text-base w-full"
                    placeholder="Your Query"
                  />
                </div>

                <div className="flex flex-col gap-2">
                  <label
                    className="text-black dark:text-white"
                    htmlFor="email-input"
                  >
                    Your Email Address
                  </label>
                  <input
                    name="email-input"
                    required
                    aria-required
                    id="email-input"
                    type="email"
                    value={formState.email}
                    onChange={(event) => {
                      setFormState({ ...formState, email: event.target.value });
                    }}
                    placeholder="Your Email Address"
                    className="p-2 text-black text-base w-full"
                  />
                </div>

                <button
                  type="submit"
                  className={` dark:text-black border border-black dark:bg-white w-max p-2 pli-4 ${
                    isLoading ? "disabled:opacity-50" : ""
                  }`}
                >
                  Submit
                </button>
              </form>

              <div
                className={`mlb-8 flex items-center  md:w-1/2 ${styles.hideWhenSmall}`}
              >
                <Lottie
                  speed={0.5}
                  height="100px"
                  width="100px"
                  options={defaultOptions}
                />
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
};

export default Home;
