import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

import Switch from "../components/Switch";

import styles from "../styles/Home.module.css";

import NavBar from "../components/NavBar";

import PersonalInfo from "../components/home-sections/personal-info";
import ProjectsInfo from "../components/home-sections/projects-info";
import SocialInfo from "../components/home-sections/social-info";
import ContactForm from "../components/home-sections/contact-form";

export interface FormState {
  name: string;
  email: string;
  message: string;
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gats Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={``}>
        <NavBar />
        <div
          className={`dark:bg-black bg-gray-200 dark:text-white ${styles.scrollSnaps}`}
        >
          <PersonalInfo />
          <ProjectsInfo />
          <SocialInfo />
          <ContactForm />
        </div>
      </main>
    </div>
  );
};

export default Home;
